CREATE TABLE IF NOT EXISTS gym_images (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gym_id INT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (gym_id) REFERENCES gyms(id) ON DELETE CASCADE
);
