-- Permissions: resource:action format. Assign to roles via role_permissions.
CREATE TABLE IF NOT EXISTS permissions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(120),
    description VARCHAR(255),
    module VARCHAR(50),
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO permissions (code, name, description, module) VALUES
    ('users:create', 'Create users', 'Create any user (admin: owners; admin/owner: coaches)', 'users'),
    ('users:read', 'Read user', 'View user profile', 'users'),
    ('users:update', 'Update user', 'Edit user details', 'users'),
    ('users:delete', 'Delete user', 'Soft delete user', 'users'),
    ('users:list', 'List users', 'List users with filters', 'users'),
    ('gyms:create', 'Create gym', 'Create gym (owner)', 'gyms'),
    ('gyms:read', 'Read gym', 'View gym details', 'gyms'),
    ('gyms:update', 'Update gym', 'Edit own gym', 'gyms'),
    ('gyms:delete', 'Delete gym', 'Soft delete gym', 'gyms'),
    ('gyms:list', 'List gyms', 'List/search gyms', 'gyms'),
    ('coaches:create', 'Create coach', 'Assign coach to gym (admin/owner)', 'coaches'),
    ('coaches:read', 'Read coach', 'View coach profile', 'coaches'),
    ('coaches:update', 'Update coach', 'Edit coach (admin/owner)', 'coaches'),
    ('coaches:delete', 'Delete coach', 'Remove coach from gym', 'coaches'),
    ('coaches:list', 'List coaches', 'List coaches by gym', 'coaches'),
    ('coach_availability:manage', 'Manage availability', 'Set own availability (coach)', 'coaches'),
    ('subscription_plans:create', 'Create plan', 'Create subscription plan (owner)', 'subscriptions'),
    ('subscription_plans:read', 'Read plan', 'View plan details', 'subscriptions'),
    ('subscription_plans:update', 'Update plan', 'Edit plan', 'subscriptions'),
    ('subscription_plans:delete', 'Delete plan', 'Soft delete plan', 'subscriptions'),
    ('subscription_plans:list', 'List plans', 'List plans by gym', 'subscriptions'),
    ('user_subscriptions:create', 'Create subscription', 'Subscribe user to plan', 'subscriptions'),
    ('user_subscriptions:read', 'Read subscription', 'View subscription', 'subscriptions'),
    ('user_subscriptions:list', 'List subscriptions', 'List user/gym subscriptions', 'subscriptions'),
    ('sessions:create', 'Create session', 'Book session (user/coach)', 'sessions'),
    ('sessions:read', 'Read session', 'View session details', 'sessions'),
    ('sessions:update', 'Update session', 'Reschedule/cancel', 'sessions'),
    ('sessions:delete', 'Delete session', 'Cancel session', 'sessions'),
    ('sessions:list', 'List sessions', 'List sessions', 'sessions'),
    ('ratings:create', 'Create rating', 'Rate gym (user)', 'ratings'),
    ('ratings:read', 'Read rating', 'View ratings', 'ratings'),
    ('ratings:delete', 'Delete rating', 'Remove rating (admin/owner)', 'ratings'),
    ('ratings:list', 'List ratings', 'List gym ratings', 'ratings'),
    ('notifications:read', 'Read notification', 'View notification', 'notifications'),
    ('notifications:update', 'Update notification', 'Mark as read', 'notifications'),
    ('notifications:list', 'List notifications', 'List user notifications', 'notifications'),
    ('payments:create', 'Create payment', 'Record payment', 'payments'),
    ('payments:read', 'Read payment', 'View payment', 'payments'),
    ('payments:list', 'List payments', 'List payments', 'payments')
ON DUPLICATE KEY UPDATE name = VALUES(name), description = VALUES(description), module = VALUES(module);
