CREATE TABLE IF NOT EXISTS user_cards (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  user_id     INT NOT NULL,
  card_label  VARCHAR(50)  NOT NULL DEFAULT 'My Card',
  card_holder VARCHAR(100) NOT NULL,
  card_last4  CHAR(4)      NOT NULL,
  card_brand  VARCHAR(20)  NOT NULL DEFAULT 'visa',
  card_expiry VARCHAR(5)   NOT NULL,
  is_default  TINYINT(1)   NOT NULL DEFAULT 0,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at  TIMESTAMP    NULL     DEFAULT NULL,
  CONSTRAINT fk_user_cards_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
